import { z } from "zod";

export const ManufacturerEnum = z.enum([
    "HONDA", "YAMAHA", "KAWASAKI", "SUZUKI", "HARLEY_DAVIDSON", "DUCATI", "BMW_MOTORRAD", "KTM", 
    "KOVE", "TRIUMPH", "ROYAL_ENFIELD", "APRILIA", "MV_AGUSTA", "INDIAN_MOTORCYCLE", "MOTO_GUZZI",
    "BAJAJ", "PIAGGIO", "HYOSUNG", "CFMOTO", "BENELLI", "ZERO_MOTORCYCLES", "HUSQVARNA", "VICTORY", 
    "URAL", "SYM", "KYMCO", "BIMOTA", "MORBIDELLI", "LAMBRETTA", "QJ_MOTOR", "NORTON"]);
  
export const CategoryEnum = z.enum([
    "ADVENTURE", "NAKED", "SUPERSPORT", "CRUISER", "TOURING", "DUAL_SPORT", "SCOOTER", "UNDERBONE",
    "ENDURO", "CAFE_RACER", "SCRAMBLER", "SPORT_TOURING", "MOTOCROSS", "ELECTRIC", "CUSTOM", "SIDECAR",]);
