import type { Metadata } from "next";
import "./globals.css";
import MainNavigation from "@/components/main-header/MainNavigation";
import { QueryProvider } from "@/components/providers/QueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className="bg-background-color">
        <MainNavigation />
        <QueryProvider>
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
