import type { Metadata } from "next";
import "./globals.css";
import MainNavigation from "@/components/main-header/MainNavigation";
import { QueryProvider } from "@/components/providers/QueryProvider";
import CompareSelectionPanel from "@/components/comparison/CompareSelectionPanel";
import AuthProvider from "@/components/AuthProvider";
import { ThemeProvider } from "@/components/ThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <script src="https://accounts.google.com/gsi/client" async defer></script>
      </head>
      <body>
        <ThemeProvider>
          <AuthProvider>
            <MainNavigation />
            <QueryProvider>
              {children}
              <CompareSelectionPanel />
            </QueryProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
